### ISSUE TITLE
Partial content will prevent the server from overloading

### ISSUE THREAD

**Issue by duongcao-ea** [nghiant3223/handbook#3]
`Partial content: the server returns just a portion of the content the user requests.` will help to fix server overload. Does anyone know the reason?

**Comment by nghiant3223** [comment]
To transfer a GB file over network, one server must load this big file into memory and append entire binary data to response body. Apparently, this causes server to suffer a lot especially on high traffic hour.  Also, this makes network overwhelmed. To fix this, you can use a buffer, load big file by chunk and sent response with partial content.
