### ISSUE TITLE
Caching reduces server load?

### ISSUE THREAD

**Issue by duongcao-ea** [nghiant3223/handbook#5]
`By adding caches to our servers, we can avoid reading the webpage or data directly from the server, thus reducing both the response time and the load on our server. This helps in making our application more scalable.`
With cache, we can reduce db load, why can it reduce server load?
And why it makes our app more scalable?

**Comment by nghiant3223** [comment]
The content may be cached at CDN, proxy!

**Comment by duongcao-ea** [comment]
Thanks! So the `server` mentioned here `By adding caches to our servers, we can avoid reading the webpage or data directly from the server`, the one in the first clause is CDN or proxy `server` and the second term is application `server`
